# Site settings
 title: ¿Qué son las humanidades digitales?
 author: 
 name: 
 email: luis17erl@gmail.com
 description: "Diferencias entre dos posturas sobre estos temas" 
 Isabel Galina

Establece un posible origen de las HD, a saber, cuando, en 1949, las obras completas de Tomás de Aquino fueron pasadas a tarjetas perforadas.
Se definen las HD, el término se refiere a como se relacionan las tecnologías de computación con las investigaciones humanísticas.
Es un campo interdisciplinario.
Establece los objetivos de las HD.
Algunos de los indicadores de que un nuevo campo, en este caso las HD, está emergiendo es que se comienzan a formar asociaciones, organizaciones, centros especializados, etc.
Habla sobre las humanidades digitales en México.
Las herramientas que proporcionan las HD pueden ser de mucha ayuda en el que hacer de la investigación.
Subraya lo prometedor que se ha vuelto este campo por todas las posibilidades que ofrece en cuanto a la investigación de las humanidades.

Gimena del Rio
No establece un origen preciso de las HD. Más bien, cree que se tienen algunos mitos para explicar su surgimiento, por ejemplo, el traspaso de las obras de Aquino a tarjetas perforadas.
No da una definición de que son las HD, pues debido a la cantidad de factores que influyen en ésta al momento de determinarla aun no hay un consenso global.
Distingue entre los términos Digital Humanities y Humanidades Digitales, los cuales se refieren, respectivamente, al mundo de habla inglesa y al de habla hispana.
Las HD atraviesan diversas disciplinas.
No se establecen objetivos de las HD.
Habla sobre las humanidades digitales en México, pero también en Argentina y España.
Las HD apoyan la labor de las humanidades al brindar la posibilidad de digital documentos y servirse de la tecnología para quehaceres humanísticos.
